CREATE TABLE "candidate_words" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "term" VARCHAR(100) NOT NULL,
    "source_type" TEXT NOT NULL,
    "source_reference" VARCHAR(255),
    "context_snippet" TEXT,
    "raw_definition" TEXT,
    "etymology_preview" TEXT,
    "part_of_speech" VARCHAR(50),
    "utility_score" NUMERIC(5, 3) DEFAULT 0.000,
    "rarity_indicators" JSONB,
    "date_discovered" DATE DEFAULT CURRENT_DATE,
    "review_status" TEXT DEFAULT 'pending',
    "rejection_reason" VARCHAR(255),
    "notes" TEXT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "defined" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "term" VARCHAR(100),
    "part_of_speech" VARCHAR(50),
    "definition" TEXT,
    "quizzed" INTEGER,
    "correct2" INTEGER,
    "date_added" DATE,
    "frequency" DOUBLE PRECISION,
    "wav_url" VARCHAR(255),
    "word_source" VARCHAR(100),
    "definition_source" VARCHAR(100),
    "bad" INTEGER,
    "freq_src" TEXT,
    "len" INTEGER,
    "phrase" INTEGER,
    "hyphenated" INTEGER,
    "has_circular_definition" BOOLEAN DEFAULT FALSE,
    "corrected_definition" TEXT,
    "needs_manual_circularity_review" BOOLEAN DEFAULT FALSE,
    "python_wordfreq" REAL,
    "ngram_freq" DOUBLE PRECISION,
    "commoncrawl_freq" NUMERIC(8, 3),
    "definition_reliability" NUMERIC(3, 2),
    "definition_updated" TIMESTAMP,
    "final_rarity" NUMERIC(8, 6),
    PRIMARY KEY ("id")
);

CREATE TABLE "defined_bu" (
    "id" INTEGER NOT NULL DEFAULT 0,
    "term" VARCHAR(100),
    "part_of_speech" VARCHAR(50),
    "definition" TEXT,
    "quizzed" INTEGER,
    "correct2" INTEGER,
    "date_added" DATE,
    "frequency" DOUBLE PRECISION,
    "wav_url" VARCHAR(255),
    "word_source" VARCHAR(100),
    "definition_source" VARCHAR(100),
    "bad" INTEGER,
    "freq_src" TEXT,
    "len" INTEGER,
    "phrase" INTEGER,
    "hyphenated" INTEGER,
    "has_circular_definition" BOOLEAN DEFAULT FALSE,
    "corrected_definition" TEXT,
    "needs_manual_circularity_review" BOOLEAN DEFAULT FALSE
);

CREATE TABLE "definition_embeddings" (
    "word_id" INTEGER NOT NULL,
    "word" VARCHAR(255) NOT NULL,
    "definition_text" TEXT NOT NULL,
    "embedding_json" TEXT,
    "embedding_model" VARCHAR(100),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("word_id")
);

CREATE TABLE "definition_similarity" (
    "word1_id" INTEGER NOT NULL,
    "word2_id" INTEGER NOT NULL,
    "cosine_similarity" NUMERIC(6, 5),
    "embedding_model" VARCHAR(100) NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("word1_id", "word2_id", "embedding_model")
);

CREATE TABLE "documents" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "source_id" INTEGER NOT NULL,
    "external_id" VARCHAR(255),
    "title" TEXT,
    "url" TEXT,
    "published_at" TIMESTAMP,
    "fetched_at" TIMESTAMP NOT NULL,
    "hash" CHAR(64) NOT NULL,
    "lang" VARCHAR(8),
    PRIMARY KEY ("id")
);

CREATE TABLE "domains" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "flashcard_deck_items" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "deck_id" INTEGER NOT NULL,
    "word_id" INTEGER NOT NULL,
    "added_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "flashcard_decks" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "user_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "harvester_config" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "source_type" VARCHAR(50) NOT NULL,
    "config_key" VARCHAR(100) NOT NULL,
    "config_value" TEXT,
    "description" TEXT,
    "last_updated" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "harvesting_sessions" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "source_type" VARCHAR(50) NOT NULL,
    "session_start" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "session_end" TIMESTAMP,
    "total_processed" INTEGER DEFAULT 0,
    "candidates_found" INTEGER DEFAULT 0,
    "candidates_accepted" INTEGER DEFAULT 0,
    "avg_utility_score" NUMERIC(5, 3) DEFAULT 0.000,
    "categories_processed" TEXT,
    "status" TEXT DEFAULT 'running',
    "error_message" TEXT,
    "notes" TEXT,
    PRIMARY KEY ("id")
);

CREATE TABLE "pronunciation_similarity" (
    "word1_id" INTEGER NOT NULL,
    "word2_id" INTEGER NOT NULL,
    "overall_similarity" NUMERIC(6, 5),
    "phonetic_distance" NUMERIC(6, 5),
    "stress_similarity" NUMERIC(6, 5),
    "rhyme_score" NUMERIC(6, 5),
    "syllable_similarity" NUMERIC(6, 5),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("word1_id", "word2_id")
);

CREATE TABLE "quiz_sessions" (
    "id" VARCHAR(50) NOT NULL,
    "user_id" INTEGER,
    "started_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMP,
    "quiz_type" VARCHAR(20),
    "difficulty" VARCHAR(20),
    "topic_domain" VARCHAR(100),
    "topic_pos" VARCHAR(50),
    "total_questions" INTEGER,
    "correct_answers" INTEGER DEFAULT 0,
    "session_config" JSONB,
    PRIMARY KEY ("id")
);

CREATE TABLE "sources" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "type" VARCHAR(64) NOT NULL,
    "url" TEXT,
    "license" VARCHAR(255),
    "enabled" BOOLEAN NOT NULL DEFAULT TRUE,
    "added_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "spider_sessions" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "session_id" VARCHAR(100) NOT NULL,
    "start_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "end_time" TIMESTAMP,
    "total_urls_visited" INTEGER DEFAULT 0,
    "total_candidates_found" INTEGER DEFAULT 0,
    "sources_used" TEXT,
    "session_config" TEXT,
    "status" TEXT DEFAULT 'running',
    PRIMARY KEY ("id")
);

CREATE TABLE "spider_source_performance" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "source_type" TEXT NOT NULL,
    "date_tracked" DATE NOT NULL,
    "urls_visited" INTEGER DEFAULT 0,
    "success_rate" NUMERIC(5, 2) DEFAULT 0.00,
    "avg_candidates_per_url" NUMERIC(8, 2) DEFAULT 0.00,
    "avg_response_time_ms" INTEGER DEFAULT 0,
    "error_count" INTEGER DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE "spider_visited_urls" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "url" VARCHAR(2000) NOT NULL,
    "url_hash" VARCHAR(64) NOT NULL,
    "source_type" TEXT NOT NULL,
    "first_visited" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "last_visited" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "visit_count" INTEGER DEFAULT 1,
    "success_count" INTEGER DEFAULT 0,
    "candidates_found" INTEGER DEFAULT 0,
    "status" TEXT DEFAULT 'success',
    PRIMARY KEY ("id")
);

CREATE TABLE "user_flashcard_progress" (
    "user_id" INTEGER NOT NULL,
    "word_id" INTEGER NOT NULL,
    "mastery_level" TEXT DEFAULT 'learning',
    "study_count" INTEGER DEFAULT 0,
    "correct_count" INTEGER DEFAULT 0,
    "last_studied" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "next_review" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "interval_days" INTEGER DEFAULT 1,
    "ease_factor" REAL DEFAULT 2.5,
    PRIMARY KEY ("user_id", "word_id")
);

CREATE TABLE "user_quiz_results" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" INTEGER NOT NULL,
    "word_id" INTEGER NOT NULL,
    "question_type" TEXT NOT NULL,
    "is_correct" BOOLEAN NOT NULL,
    "response_time_ms" INTEGER,
    "answered_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "difficulty_level" TEXT DEFAULT 'medium',
    "session_id" VARCHAR(50),
    PRIMARY KEY ("id")
);

CREATE TABLE "user_word_mastery" (
    "user_id" INTEGER NOT NULL,
    "word_id" INTEGER NOT NULL,
    "mastery_level" TEXT DEFAULT 'learning',
    "total_attempts" INTEGER DEFAULT 0,
    "correct_attempts" INTEGER DEFAULT 0,
    "last_seen" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "next_review" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "streak" INTEGER DEFAULT 0,
    "ease_factor" REAL DEFAULT 2.5,
    PRIMARY KEY ("user_id", "word_id")
);

CREATE TABLE "users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "username" VARCHAR(50) NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "full_name" VARCHAR(255),
    "password_hash" VARCHAR(255) NOT NULL,
    "role" TEXT DEFAULT 'user',
    "is_active" BOOLEAN DEFAULT TRUE,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "last_login_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "word_domains" (
    "word_id" INTEGER NOT NULL,
    "primary_domain" VARCHAR(100),
    "domain_id" INTEGER,
    PRIMARY KEY ("word_id")
);

CREATE TABLE "word_frequencies_independent" (
    "word_id" INTEGER NOT NULL,
    "term" VARCHAR(255),
    "independent_frequency" DOUBLE PRECISION,
    "original_frequency" NUMERIC(15, 8),
    "source_frequencies" JSONB,
    "method_count" INTEGER,
    "frequency_rank" INTEGER,
    "rarity_percentile" NUMERIC(5, 2),
    "calculation_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("word_id")
);

CREATE TABLE "word_frequency_data" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "word" VARCHAR(100) NOT NULL,
    "source" VARCHAR(50) NOT NULL,
    "zipf_score" NUMERIC(6, 3) DEFAULT 0.000,
    "raw_frequency" NUMERIC(15, 10) DEFAULT 0.0000000000,
    "confidence" NUMERIC(4, 3) DEFAULT 0.000,
    "collection_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "metadata" JSONB,
    "composite_zipf" NUMERIC(6, 3) DEFAULT 0.000,
    "composite_confidence" NUMERIC(4, 3) DEFAULT 0.000,
    PRIMARY KEY ("id")
);

CREATE TABLE "word_phonetics" (
    "word_id" INTEGER NOT NULL,
    "word" VARCHAR(255) NOT NULL,
    "ipa_transcription" TEXT,
    "arpabet_transcription" TEXT,
    "syllable_count" INTEGER,
    "stress_pattern" VARCHAR(50),
    "phonemes_json" TEXT,
    "transcription_source" VARCHAR(50),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("word_id")
);
